"""Initial migration

Revision ID: bf5b0547f499
Revises: 
Create Date: 2025-12-08 14:43:14.311785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5b0547f499'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('dept_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dept_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('dept_id')
    )
    op.create_index(op.f('ix_departments_dept_name'), 'departments', ['dept_name'], unique=True)
    op.create_table('record_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=True),
    sa.Column('defaults_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_templates_name'), 'record_templates', ['name'], unique=False)
    op.create_index(op.f('ix_record_templates_scope'), 'record_templates', ['scope'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=19), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('prescriptions_json', sa.Text(), nullable=True),
    sa.Column('labs_json', sa.Text(), nullable=True),
    sa.Column('imaging_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_created_at'), 'records', ['created_at'], unique=False)
    op.create_index(op.f('ix_records_dept_id'), 'records', ['dept_id'], unique=False)
    op.create_index(op.f('ix_records_doctor_id'), 'records', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_records_patient_name'), 'records', ['patient_name'], unique=False)
    op.create_index(op.f('ix_records_status'), 'records', ['status'], unique=False)
    op.create_index(op.f('ix_records_template_id'), 'records', ['template_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('real_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('doctors',
    sa.Column('doctor_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('doctor_name', sa.String(length=50), nullable=False),
    sa.Column('dept_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('available_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_index(op.f('ix_doctors_available_status'), 'doctors', ['available_status'], unique=False)
    op.create_index(op.f('ix_doctors_dept_id'), 'doctors', ['dept_id'], unique=False)
    op.create_index(op.f('ix_doctors_doctor_name'), 'doctors', ['doctor_name'], unique=False)
    op.create_index(op.f('ix_doctors_user_id'), 'doctors', ['user_id'], unique=True)
    op.create_table('patients',
    sa.Column('patient_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('id_card', sa.String(length=18), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact', sa.String(length=50), nullable=True),
    sa.Column('emergency_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('id_card')
    )
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=True)
    op.create_table('doctor_schedules',
    sa.Column('schedule_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('max_appointments', sa.Integer(), nullable=False),
    sa.Column('booked', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_doctor_schedules_doctor_id'), 'doctor_schedules', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_schedules_status'), 'doctor_schedules', ['status'], unique=False)
    op.create_index(op.f('ix_doctor_schedules_work_date'), 'doctor_schedules', ['work_date'], unique=False)
    op.create_table('appointments',
    sa.Column('appt_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('appt_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('symptom_desc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['doctor_schedules.schedule_id'], ),
    sa.PrimaryKeyConstraint('appt_id')
    )
    op.create_index(op.f('ix_appointments_appt_time'), 'appointments', ['appt_time'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_schedule_id'), 'appointments', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_schedule_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appt_time'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_doctor_schedules_work_date'), table_name='doctor_schedules')
    op.drop_index(op.f('ix_doctor_schedules_status'), table_name='doctor_schedules')
    op.drop_index(op.f('ix_doctor_schedules_doctor_id'), table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_doctors_user_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_doctor_name'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_dept_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_available_status'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_records_template_id'), table_name='records')
    op.drop_index(op.f('ix_records_status'), table_name='records')
    op.drop_index(op.f('ix_records_patient_name'), table_name='records')
    op.drop_index(op.f('ix_records_doctor_id'), table_name='records')
    op.drop_index(op.f('ix_records_dept_id'), table_name='records')
    op.drop_index(op.f('ix_records_created_at'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_record_templates_scope'), table_name='record_templates')
    op.drop_index(op.f('ix_record_templates_name'), table_name='record_templates')
    op.drop_table('record_templates')
    op.drop_index(op.f('ix_departments_dept_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
